### ISSUE TITLE
--filter pixesort doesn't work with RGBA (only with RGB)

### ISSUE THREAD

**Issue by s3h10r** [s3h10r/egw-plugins#3]
```
Traceback (most recent call last):
  File "/home/s3h10r/development/einguteswerkzeug/tmp/venv_egw/bin/egw", line 69, in <module>
    main(args)
  File "/home/s3h10r/development/einguteswerkzeug/tmp/venv_egw/lib/python3.6/site-packages/einguteswerkzeug/core/__init__.py", line 584, in main
    img = _apply_filters(image=source, filters = apply_filters, filters_args = [])
  File "/home/s3h10r/development/einguteswerkzeug/tmp/venv_egw/lib/python3.6/site-packages/einguteswerkzeug/core/__init__.py", line 433, in _apply_filters
    img = PLUGINS_FILTERS[edit_filter].run(**kwargs)
  File "/home/s3h10r/development/einguteswerkzeug/tmp/venv_egw/lib/python3.6/site-packages/einguteswerkzeug/core/../plugins/filters/pixelsort.py", line 43, in run
    return _do_pixelsort(image, algo)
  File "/home/s3h10r/development/einguteswerkzeug/tmp/venv_egw/lib/python3.6/site-packages/einguteswerkzeug/core/../plugins/filters/pixelsort.py", line 87, in _do_pixelsort
    [r, g, b] = img_in_pixels[x, y]
ValueError: too many values to unpack (expected 3)

```
 `test_plugin-params.sh`:
```console 
egw --generator nlines --clockwise --params-generator='{"seed" : 5269546439996500824, "nr_lines" : 9, "x_step" : 20, "thickness" : 6, "color" : [0,255,0,255], "bg_color" : [0,0,200,255]}' -o $FOUT  --filter quads,invert,oil,pixelsort --params-filter='{"mode" : 1, "iterations" : 256}{}{"brush_size" : 2, "roughness" : 50}' --config $CONFIG --template $TPL  --title "quad-filtered generator nlines (variant b), 2019 #einguteswerkzeug" --max-size 800 || exit 1
feh $FOUT
```

**Comment by s3h10r** [comment]
fixed
